// Rashid - generates real, downloadable PDF files (via jsPDF) instead of
// placeholder alerts. Where the report reflects the user's own wizard
// input, it pulls the numbers from RashidCalc.analyze() so the PDF matches
// whatever is shown on screen.
window.RashidReport = (function () {
    function getJsPDF() {
        if (!window.jspdf || !window.jspdf.jsPDF) {
            alert('تعذر تحميل مكوّن إنشاء PDF. تحقق من اتصالك بالإنترنت وحاول مرة أخرى.');
            return null;
        }
        return window.jspdf.jsPDF;
    }

    function baseDoc() {
        const JsPDF = getJsPDF();
        if (!JsPDF) return null;
        return new JsPDF({ unit: 'pt', format: 'a4' });
    }

    function header(doc, title, subtitle) {
        doc.setFillColor(24, 21, 18);
        doc.rect(0, 0, 595, 90, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(20);
        doc.text('Rashid - Responsible Lending Intelligence', 40, 42);
        doc.setFontSize(12);
        doc.setTextColor(213, 178, 115);
        doc.text(title, 40, 65);
        if (subtitle) {
            doc.setFontSize(9);
            doc.setTextColor(210, 205, 198);
            doc.text(subtitle, 40, 80);
        }
        doc.setTextColor(20, 20, 20);
    }

    function footer(doc) {
        doc.setFontSize(8);
        doc.setTextColor(140, 140, 140);
        doc.text(
            'Auto-generated by the Rashid platform on ' + new Date().toLocaleString('en-GB') +
            '. For demo purposes only - not a formal credit decision.',
            40, 800
        );
    }

    function row(doc, y, label, value) {
        doc.setFontSize(11);
        doc.setTextColor(100, 90, 80);
        doc.text(label, 40, y);
        doc.setFontSize(12);
        doc.setTextColor(20, 20, 20);
        doc.text(String(value), 300, y);
        doc.setDrawColor(230, 225, 218);
        doc.line(40, y + 8, 555, y + 8);
    }

    function sectionTitle(doc, y, text) {
        doc.setFontSize(13);
        doc.setTextColor(24, 21, 18);
        doc.text(text, 40, y);
        return y + 24;
    }

    function downloadAnalysisPdf() {
        const doc = baseDoc();
        if (!doc) return;
        const result = RashidCalc.analyze();
        header(doc, 'Loan Readiness Analysis Report', 'Applicant: ' + (result.input.name || 'Rashid Customer'));

        let y = 130;
        y = sectionTitle(doc, y, 'Application Summary');
        row(doc, y, 'Monthly Income', result.input.income.toLocaleString() + ' SAR'); y += 26;
        row(doc, y, 'Requested Amount', result.input.amount.toLocaleString() + ' SAR'); y += 26;
        row(doc, y, 'Repayment Tenure', result.input.tenure + ' months'); y += 26;
        row(doc, y, 'Current Monthly Obligations', result.input.obligations.toLocaleString() + ' SAR'); y += 40;

        y = sectionTitle(doc, y, 'Rashid AI Analysis');
        row(doc, y, 'Estimated New Installment', result.installment.toLocaleString() + ' SAR/mo'); y += 26;
        row(doc, y, 'Total Monthly Obligations', result.totalObligations.toLocaleString() + ' SAR/mo'); y += 26;
        row(doc, y, 'Debt Burden Ratio (DBR)', result.burdenRatio + '%'); y += 26;
        row(doc, y, 'Maximum Allowed DBR (SAMA-style cap)', result.burdenCap + '%'); y += 26;
        row(doc, y, 'Projected Monthly Surplus', result.surplus.toLocaleString() + ' SAR'); y += 26;
        row(doc, y, 'Financial Pressure Score', result.pressureScore + ' / 100'); y += 26;
        row(doc, y, 'Financial Readiness', result.readiness); y += 26;
        row(doc, y, 'Analysis Confidence', result.confidence + '%'); y += 26;
        row(doc, y, 'Decision', result.decision); y += 40;

        y = sectionTitle(doc, y, 'Recommendation');
        doc.setFontSize(11);
        doc.setTextColor(60, 60, 60);
        doc.text(doc.splitTextToSize(result.recommendation, 515), 40, y);

        footer(doc);
        doc.save('rashid-analysis-report.pdf');
    }

    function downloadDecisionPdf() {
        const doc = baseDoc();
        if (!doc) return;
        const result = RashidCalc.analyze();

        let selected = null;
        try { selected = JSON.parse(localStorage.getItem('rashidSelectedOffer') || 'null'); } catch (e) {}
        if (!selected) {
            const offers = RashidCalc.alternativeOffers();
            selected = { key: 'safe', label: 'Safe Offer', amount: offers.safe.amount, tenure: offers.safe.tenure, installment: offers.safe.installment };
        }
        const ctx = window.__rashidDecisionContext;

        header(doc, 'Final Decision Summary', 'Applicant: ' + (result.input.name || 'Rashid Customer'));

        let y = 130;
        y = sectionTitle(doc, y, 'Decision Fingerprint');
        row(doc, y, 'Final Decision', result.decision); y += 26;
        row(doc, y, 'Selected Offer', selected.label); y += 26;
        row(doc, y, 'Selected Amount', selected.amount.toLocaleString() + ' SAR'); y += 26;
        row(doc, y, 'Selected Tenure', selected.tenure + ' months'); y += 26;
        row(doc, y, 'Confidence', result.confidence + '%'); y += 40;

        y = sectionTitle(doc, y, 'Original Request vs. Selected Offer');
        row(doc, y, 'Financing Amount - Original', (ctx ? ctx.originalAmount : result.input.amount).toLocaleString() + ' SAR'); y += 22;
        row(doc, y, 'Financing Amount - Selected', selected.amount.toLocaleString() + ' SAR'); y += 26;
        row(doc, y, 'Monthly Installment - Original', Math.round(ctx ? ctx.originalInstallment : result.installment).toLocaleString() + ' SAR'); y += 22;
        row(doc, y, 'Monthly Installment - Selected', selected.installment.toLocaleString() + ' SAR'); y += 26;
        row(doc, y, 'Total Monthly Obligations - Original', ctx ? (Math.round(ctx.originalTotal).toLocaleString() + ' SAR (' + ctx.originalBurdenPct + '%)') : '-'); y += 22;
        row(doc, y, 'Total Monthly Obligations - Selected', ctx ? (Math.round(ctx.selectedTotal).toLocaleString() + ' SAR (' + ctx.selectedBurdenPct + '%)') : '-'); y += 26;
        row(doc, y, 'Remaining at Month End - Original', ctx && ctx.originalRemaining !== null ? Math.round(ctx.originalRemaining).toLocaleString() + ' SAR' : '-'); y += 22;
        row(doc, y, 'Remaining at Month End - Selected', ctx && ctx.selectedRemaining !== null ? Math.round(ctx.selectedRemaining).toLocaleString() + ' SAR' : '-'); y += 40;

        y = sectionTitle(doc, y, 'Notes');
        doc.setFontSize(11);
        doc.setTextColor(60, 60, 60);
        doc.text(doc.splitTextToSize(result.recommendation, 515), 40, y);

        footer(doc);
        doc.save('rashid-decision-summary.pdf');
    }

    function downloadRequestSummaryPdf() {
        const doc = baseDoc();
        if (!doc) return;
        header(doc, 'Loan Request Analysis Summary', 'Request ID: REQ-8829-XPL');

        let y = 130;
        y = sectionTitle(doc, y, 'Customer');
        row(doc, y, 'Name', 'Omar Al-Farsi'); y += 26;
        row(doc, y, 'Tier', 'Priority Customer - Platinum Tier'); y += 26;
        row(doc, y, 'Product', 'Commercial Expansion Loan'); y += 26;
        row(doc, y, 'Requested Amount', '2,450,000 SAR'); y += 40;

        y = sectionTitle(doc, y, 'AI Intelligence Score');
        row(doc, y, 'Financial Readiness', '89%'); y += 26;
        row(doc, y, 'Eligibility Index', '76%'); y += 26;
        row(doc, y, 'Approval Probability', 'High'); y += 40;

        y = sectionTitle(doc, y, 'Recommended Offer');
        row(doc, y, 'Plan', 'Gold Tier Standard'); y += 26;
        row(doc, y, 'Rate', '4.25%'); y += 26;
        row(doc, y, 'Tenor', '60 months'); y += 26;
        row(doc, y, 'LTV', '75%'); y += 26;

        footer(doc);
        doc.save('rashid-request-REQ-8829-XPL.pdf');
    }

    function downloadDashboardReportPdf() {
        const doc = baseDoc();
        if (!doc) return;
        header(doc, 'Quarterly Advisor Intelligence Report', 'Portfolio overview - Q2 2026');

        let y = 130;
        y = sectionTitle(doc, y, 'Portfolio Metrics');
        row(doc, y, 'Total Requests', '1,248'); y += 26;
        row(doc, y, 'High-Pressure Requests', '248 (Urgent)'); y += 26;
        row(doc, y, 'Avg. Pressure Reduction', '18%'); y += 26;
        row(doc, y, 'Alternative Offer Conversion', '42%'); y += 40;

        y = sectionTitle(doc, y, 'AI Impact');
        doc.setFontSize(11);
        doc.setTextColor(60, 60, 60);
        doc.text(doc.splitTextToSize(
            "Rashid's pressure-detection algorithm reduced overall credit risk by 14% in the last quarter by identifying high-stress applicants earlier.",
            515
        ), 40, y);

        footer(doc);
        doc.save('rashid-advisor-quarterly-report.pdf');
    }

    return {
        downloadAnalysisPdf,
        downloadDecisionPdf,
        downloadRequestSummaryPdf,
        downloadDashboardReportPdf
    };
})();
